all : clientudp Servudp

clientudp_etape1 : clientudp.c
	cc -Wall -Werror -o clientudp clientudp.c
Serverudp_etape1 : Servudp.c
	cc -Wall -Werror -o Servudp Servudp.c

clean :
	rm -f clientudp Servudp